import ast
from pathlib import Path
from sys import stderr
from typing import Generator
from warnings import warn


from .helpers import walk_dict
from .api_call import def_api_call
from .schema_objects import TypedDictSpec, FuncArg, ApiCall
from .annotations import get_annotations, Argument, Property

DOCSTRING = "This code was automatically generated by https://github.com/yunruse/openapi-transmog."

SETUP = ast.parse('''\
from typing import TypedDict, Literal
from os.path import expandvars

from requests import request

from dotenv import load_dotenv
load_dotenv()
''')


def _obj_defs(obj_specs: dict[str, dict], properties: dict[str, dict[str, Property]]):
    for name, obj_spec in obj_specs.items():
        yield TypedDictSpec.from_api_spec(name, obj_spec, properties.get(name, {}))


def scan_ref_imbue(obj_specs: dict[str, dict]):
    for dictionary in walk_dict(obj_specs):
        if '$ref' not in dictionary:
            continue
        obj_def = dict(dictionary)
        ref = obj_def.pop('$ref').removeprefix('#/components/schemas/')
        if obj_def:
            obj_specs.setdefault(ref, {}).update(obj_def)


def func_def_name(url: str):
    # TODO: fancier wrangling
    return '_'.join([
        seg for seg in url.removeprefix('/').removesuffix('/').split('/')
        if not seg.startswith('{')
    ])


def _func_defs(schema: dict, arguments: dict[str, dict[str, Argument]]):
    for path, m_spec in schema.get('paths', {}).items():
        for method, path_spec in m_spec.items():
            if method == 'servers':
                continue

            name = func_def_name(path)

            yield ApiCall.from_api_spec(
                func_def_name(path), path, method, path_spec, arguments.get(name, {}))


def _base_url(schema: dict) -> str:
    base_url = schema.get('servers', [{}])[0].get('url')

    for _, m_spec in schema.get('paths', {}).items():
        if len(bu := m_spec.pop('servers', [])):
            base_url = bu[0].get('url')
            # HACK: this does NOT handle the case in which there are muliple servers...

    if not base_url:
        base_url = 'https://example.org'
        warn(f'The schema does not define a base URL! The code will use {base_url}')
    return base_url


def has_docstring(body: list[ast.expr]):
    if len(body):
        if isinstance(body[0], ast.Expr):
            if isinstance(body[0].value, ast.Constant):
                return isinstance(body[0].value.value, str)
    return False


def generate_code(
    schema: dict,
    params: dict[str, str] = None,
    headers: dict[str, str] = None,
    cookies: dict[str, str] = None,
    auth: tuple[str, str] = None,
    annotation_fp: Path = None
):

    body = []

    # TODO: parse the .info; useful stuff!!

    if annotation_fp is not None:
        user_body, arguments, properties = get_annotations(annotation_fp)
        pass
    else:
        user_body = []
        arguments = {}
        properties = {}

    if not has_docstring(user_body):
        body.append(ast.Expr(ast.Constant(DOCSTRING)))

    # TODO: strip any inlined annotators out..?
    body += user_body

    body.append(SETUP)

    funcs = list(_func_defs(schema, arguments))
    obj_defs: dict[str, dict] = schema.get('components', {}).get('schemas', {})

    for f in funcs:
        # Some function calls have 'anonymous types',
        # which we will still define.
        for name, obj_def in f.obj_extras.items():
            obj_defs.setdefault(name, {}).update(obj_def)

    scan_ref_imbue(obj_defs)

    for obj in _obj_defs(obj_defs, properties):
        body.append(obj.as_ast())

    body.append(def_api_call(
        _base_url(schema),
        params=params,
        headers=headers,
        cookies=cookies,
        auth=auth,
    ))

    for func in funcs:
        body.append(func.as_ast())

    body.append(ast.Assign(
        [ast.Name('__all__')],
        ast.List([ast.Constant(f.name) for f in funcs])
    ))

    return ast.unparse(ast.fix_missing_locations(ast.Module(body, [])))
